spring.application.name=AlgoNest_Backend

# Groq AI
groq.api.key=YOUR_GROQ_API_KEY

# Supabase
supabase.url=YOUR_SUPABASE_URL
supabase.service-role-key=YOUR_SERVICE_ROLE_KEY
supabase.jwt.secret=YOUR_JWT_SECRET
supabase.anon-key=YOUR_ANON_KEY

# Database
spring.datasource.url=YOUR_DATABASE_URL
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_EMAIL
spring.mail.password=YOUR_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Scheduling
spring.task.scheduling.enabled=true

# CORS
frontend.url=http://localhost:5173